export const REQUESTING_WEATHER = 'REQUESTING_WEATHER';
export const WEATHER_REQUEST_SUCCESS = 'WEATHER_REQUEST_SUCCESS';
export const WEATHER_REQUEST_FAILURE = 'WEATHER_REQUEST_FAILURE';

export const REQUESTING_LOCATION = 'REQUESTING_LOCATION';
export const LOCATION_REQUEST_SUCCESS = 'LOCATION_REQUEST_SUCCESS';
export const LOCATION_REQUEST_FAILURE = 'LOCATION_REQUEST_FAILURE';
